services:

  devcontainer:
    build:
      target: dev
    environment:
      - CI
      - OPENAI_API_KEY
    depends_on:
      - postgres
    # Enable GPU access via NVIDIA Container Toolkit
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [gpu]
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: raglite_user
      POSTGRES_PASSWORD: raglite_password
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  command-history-volume:
