services:

  devcontainer:
    build:
      target: dev
    environment:
      - CI
      - OPENAI_API_KEY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    depends_on:
      - postgres
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/
      - python-venv-volume:/opt/venv
      - cache-volume:/home/user/.cache
      - local-volume:/home/user/.local
      - models-volume:/home/user/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    runtime: nvidia

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: raglite_user
      POSTGRES_PASSWORD: raglite_password
    tmpfs:
      - /var/lib/postgresql/data

volumes:
  command-history-volume:
  python-venv-volume:
  cache-volume:
  local-volume:
  models-volume:
