name: "Copilot Setup Steps"
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # Python project environment variables
      PYTHON_VERSION: "3.11"
      NODE_ENV: development
      # GPU support (will be detected and configured automatically)
      OLLAMA_CUDA_SUPPORT: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Install with retry mechanism
          pip install -e .[dev,test] || pip install -e . || pip install .
          # Install SQLite dependencies with fallbacks
          pip install sqlite-vec pynndescent || echo "Some SQLite dependencies failed - continuing with fallbacks"

      - name: Setup Node.js with Yarn fallback
        run: |
          # Install yarn as fallback for npm
          npm install -g yarn || true
          # Cache Node modules if package.json exists
          if [ -f "package.json" ]; then
            npm install || yarn install || echo "Node.js dependency install failed"
          fi

      - name: Run environment setup script
        run: |
          chmod +x .github/setup-environment.sh
          ./.github/setup-environment.sh

      - name: Install Node.js for MCP (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Run tests
        run: |
          python -m pytest tests/ -v --tb=short

      - name: Validate SQLite backend
        run: |
          python -c "import sqlite3; conn = sqlite3.connect('tests/test_raglite.db'); cursor = conn.cursor(); cursor.execute('SELECT COUNT(*) FROM documents'); print(f'Documents: {cursor.fetchone()[0]}'); conn.close()"

      - name: Check documentation
        run: |
          ls -la .github/
          echo "✅ GitHub Copilot setup files present"
